-- Observaciones de actos / condiciones inseguras.
-- Las columnas de clasificación tienen el valor VIGENTE (para filtrar). El reporte tal como se
-- cargó queda congelado en original_data + original_hash (SHA-256): nunca se modifica.
CREATE TABLE IF NOT EXISTS observations (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    number INT UNSIGNED NOT NULL,
    category_id INT UNSIGNED NULL,
    risk_type_id INT UNSIGNED NULL,
    severity_id INT UNSIGNED NULL,
    site_id INT UNSIGNED NULL,
    sector_id INT UNSIGNED NULL,
    equipment_id INT UNSIGNED NULL,
    description TEXT NOT NULL,
    location_text VARCHAR(191) NULL,
    lat DECIMAL(10,7) NULL,
    lng DECIMAL(10,7) NULL,
    gps_accuracy_m INT UNSIGNED NULL,
    imminent_risk TINYINT(1) NOT NULL DEFAULT 0,
    is_anonymous TINYINT(1) NOT NULL DEFAULT 0,
    reporter_user_id INT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'abierta',
    assigned_user_id INT UNSIGNED NULL,
    action_text TEXT NULL,
    action_due_on DATE NULL,
    closed_at DATETIME NULL,
    created_at_device DATETIME NOT NULL,
    received_at DATETIME NOT NULL,
    original_data TEXT NOT NULL,
    original_hash CHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    UNIQUE KEY uq_observations_uuid (uuid),
    UNIQUE KEY uq_observations_number (number),
    KEY idx_observations_status (status, created_at_device),
    KEY idx_observations_sector (sector_id, status),
    KEY idx_observations_reporter (reporter_user_id),
    KEY idx_observations_assigned (assigned_user_id, status),
    KEY idx_observations_imminent (imminent_risk, status),
    KEY idx_observations_updated (updated_at),
    CONSTRAINT fk_observations_category FOREIGN KEY (category_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_observations_risk FOREIGN KEY (risk_type_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_observations_severity FOREIGN KEY (severity_id) REFERENCES catalog_items (id),
    CONSTRAINT fk_observations_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_observations_sector FOREIGN KEY (sector_id) REFERENCES sectors (id),
    CONSTRAINT fk_observations_equipment FOREIGN KEY (equipment_id) REFERENCES equipment (id),
    CONSTRAINT fk_observations_reporter FOREIGN KEY (reporter_user_id) REFERENCES users (id),
    CONSTRAINT fk_observations_assigned FOREIGN KEY (assigned_user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
